# Generated by Django 4.2.16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre País')),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=1, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paises_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Estado')),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=1, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estados_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Ciudad')),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=1, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciudades_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('pais', models.ForeignKey(limit_choices_to={'estado': 1}, on_delete=django.db.models.deletion.PROTECT, related_name='ciudades', to='core.pais', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='pais',
            index=models.Index(fields=['nombre'], name='core_pais_nombre_f96f2f_idx'),
        ),
        migrations.AddIndex(
            model_name='pais',
            index=models.Index(fields=['estado'], name='core_pais_estado_df932b_idx'),
        ),
        migrations.AddIndex(
            model_name='estado',
            index=models.Index(fields=['nombre'], name='core_estado_nombre_f1ab25_idx'),
        ),
        migrations.AddIndex(
            model_name='estado',
            index=models.Index(fields=['estado'], name='core_estado_estado_7561f2_idx'),
        ),
        migrations.AddIndex(
            model_name='ciudad',
            index=models.Index(fields=['nombre'], name='core_ciudad_nombre_38600c_idx'),
        ),
        migrations.AddIndex(
            model_name='ciudad',
            index=models.Index(fields=['estado'], name='core_ciudad_estado_4712f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ciudad',
            unique_together={('nombre', 'pais')},
        ),
    ]
