# Generated by Django 4.2.16 on 2026-01-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=0, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=0, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=0, verbose_name='Estado'),
        ),
    ]
