# Generated by Django 4.2.16 on 2026-01-09 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Obra')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin_estimada', models.DateField(verbose_name='Fecha Fin Estimada')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('ciudad', models.ForeignKey(limit_choices_to={'estado': True}, on_delete=django.db.models.deletion.PROTECT, related_name='obras', to='core.ciudad', verbose_name='Ciudad')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('estado_obra', models.ForeignKey(limit_choices_to={'estado': True}, on_delete=django.db.models.deletion.PROTECT, related_name='obras', to='core.estado', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'db_table': 'obras_lista',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RegistroLibroObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('observaciones', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Observaciones')),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='libro_obras/', verbose_name='Fotografía/Video')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('obra', models.ForeignKey(limit_choices_to={'estado': True}, on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='obras.obra', verbose_name='Obra')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_supervisados', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Registro Libro de Obra',
                'verbose_name_plural': 'Registros Libro de Obra',
                'db_table': 'libro_obras_registro',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TrabajadorRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Horas Trabajadas')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajadores', to='obras.registrolibroobra', verbose_name='Registro')),
                ('trabajador', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='registros_trabajados', to=settings.AUTH_USER_MODEL, verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Trabajador en Registro',
                'verbose_name_plural': 'Trabajadores en Registro',
                'db_table': 'libro_obras_trabajador',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TareaRealizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción de la Tarea')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='obras.registrolibroobra', verbose_name='Registro')),
            ],
            options={
                'verbose_name': 'Tarea Realizada',
                'verbose_name_plural': 'Tareas Realizadas',
                'db_table': 'libro_obras_tarea',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='FotografiaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='libro_obras/', verbose_name='Archivo')),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], default='imagen', max_length=10)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotografias', to='obras.registrolibroobra')),
            ],
            options={
                'verbose_name': 'Fotografía/Video',
                'verbose_name_plural': 'Fotografías/Videos',
                'db_table': 'libro_obras_foto',
                'ordering': ['orden', 'fecha_subida'],
            },
        ),
        migrations.AddIndex(
            model_name='registrolibroobra',
            index=models.Index(fields=['fecha'], name='libro_obras_fecha_b11308_idx'),
        ),
        migrations.AddIndex(
            model_name='registrolibroobra',
            index=models.Index(fields=['obra', 'fecha'], name='libro_obras_obra_id_8028ae_idx'),
        ),
        migrations.AddIndex(
            model_name='obra',
            index=models.Index(fields=['codigo'], name='obras_lista_codigo_74c2fe_idx'),
        ),
        migrations.AddIndex(
            model_name='obra',
            index=models.Index(fields=['estado'], name='obras_lista_estado_ac148d_idx'),
        ),
        migrations.AddIndex(
            model_name='fotografiaregistro',
            index=models.Index(fields=['registro', 'orden'], name='libro_obras_registr_5deb88_idx'),
        ),
    ]
