# Generated by Django 4.2.16 on 2026-01-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='estado',
        ),
        migrations.AddField(
            model_name='categoria',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='estado',
        ),
        migrations.AddField(
            model_name='gasto',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='estado',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.RemoveField(
            model_name='tipodocumento',
            name='estado',
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
