# Generated by Django 4.2.16 on 2026-01-20 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_alter_categoria_estado_alter_gasto_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='usuario',
            new_name='creado_por',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='usuario',
            new_name='creado_por',
        ),
        migrations.RenameField(
            model_name='tipodocumento',
            old_name='usuario',
            new_name='creado_por',
        ),
    ]
