# Generated by Django 4.2.16 on 2026-01-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_rename_usuario_categoria_creado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
